function [ ] = Plot_Position( position , color)
%PLOT_POINT Summary of this function goes here
%   Detailed explanation goes here

if (color == 1) 
    plot(position(1), position(2),'--rs','LineWidth',2,...
                'MarkerEdgeColor','k',...
                'MarkerFaceColor','r',...
                'MarkerSize',10);
else 
   plot(position(1), position(2),'--rs','LineWidth',2,...
                'MarkerEdgeColor','k',...
                'MarkerFaceColor','g',...
                'MarkerSize',10); 
end

end

